# Generated by Django 5.0.6 on 2024-06-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
