# Generated by Django 5.0.6 on 2024-06-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0002_remove_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
    ]
