# Generated by Django 5.0.6 on 2024-06-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0003_remove_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hours_used_per_day',
            field=models.FloatField(default=0.0),
        ),
    ]
