# Generated by Django 5.0.6 on 2024-06-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0005_alter_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='brand',
        ),
    ]
