# Generated by Django 5.0.6 on 2024-06-21 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0006_rename_name_device_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_consumption', models.FloatField()),
                ('unit', models.CharField(default='kWh', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_management.device')),
            ],
            options={
                'unique_together': {('device', 'year', 'month')},
            },
        ),
    ]
