# Generated by Django 5.0.6 on 2024-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0007_monthlyconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='allow_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='allow_text_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='disable_all_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
