# Generated by Django 5.0.6 on 2024-07-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0009_alter_notification_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
