# Generated by Django 5.0.6 on 2024-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_management', '0012_remove_notification_allow_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='allow_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='allow_text_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
